import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'abhi',
      email: 'abhi@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Laxmi sara',
      slug: 'Laxmi-sara',
      category: 'necklace',
      image: '/images/p1.jpg',
      gram: '25',
      price: 434532,
      countInStock: 10,
      brand: 'sara',
      rating: 4.5,
      numReviews: 10,
      description:
        'This Gold Laxmi Necklace has small circular coin shaped pieces with the impression of goddess Laxmi, arranged in a linear fashion on regular gaps.',
    },
    {
      name: 'Entele sara',
      slug: 'Entele-sara',
      category: 'necklace',
      image: '/images/p2.jpg',
      gram: '25',
      price: 140000,
      countInStock: 0,
      brand: 'sara-necklace',
      rating: 4.5,
      numReviews: 10,
      description: 'aestdfygg',
    },
    {
      name: 'Haram',
      slug: 'Haram',
      category: 'necklace',
      image: '/images/p3.jpg',
      gram: '25',
      price: 140000,
      countInStock: 10,
      brand: 'sara-necklace',
      rating: 4.5,
      numReviews: 10,
      description: '916 KDM HallMark Gold',
    },
    {
      name: 'Pathak',
      slug: 'Pathak',
      category: 'necklace',
      image: '/images/p4.jpg',
      gram: '25',
      price: 140000,
      countInStock: 10,
      brand: 'cobras hood',
      rating: 4.5,
      numReviews: 10,
      description: '916 KDM HallMark Gold',
    },
  ],
};
export default data;
