const data = {
  products: [
    {
      _id: '1',
      name: 'Laxmi sara',
      slug: 'Laxmi-sara',
      category: 'necklace',
      image: '/images/p1.jpg',
      gram: '25',
      price: 140000,
      countInStock: 10,
      brand: 'sara',
      rating: 4.5,
      numReviews: 10,
      description:
        'Product Code:	PJ017, Availability:	In stock, Product Metal:	Gold',
    },
    {
      _id: '2',
      name: 'Entele sara',
      slug: 'Entele-sara',
      category: 'necklace',
      image: '/images/p2.jpg',
      gram: '25',
      price: 140000,
      countInStock: 10,
      brand: 'sara-necklace',
      rating: 4.5,
      numReviews: 10,
      description: '916 KDM HallMark Gold',
    },
    {
      _id: '3',
      name: 'Haram',
      slug: 'Haram',
      category: 'necklace',
      image: '/images/p3.jpg',
      gram: '25',
      price: 140000,
      countInStock: 10,
      brand: 'sara-necklace',
      rating: 4.5,
      numReviews: 10,
      description: '916 KDM HallMark Gold',
    },
    {
      _id: '4',
      name: 'Pathak',
      slug: 'Pathak',
      category: 'necklace',
      image: '/images/p4.jpg',
      gram: '25',
      price: 140000,
      countInStock: 10,
      brand: 'cobras hood',
      rating: 4.5,
      numReviews: 10,
      description: '916 KDM HallMark Gold',
    },
  ],
};
export default data;
